### ISSUE TITLE
Testa installera partykit

### ISSUE THREAD

**Issue by JohannaMJ** [alsterverse/track-bc-gaming#1]

**Comment by alsterjim** [comment]
Jag fick igång partykit och lyckades deploya det hemifrån, ska testa från jobbet också, kan också vara problem med vilket konto man använder, jag testade med mitt privata githubkonto och hade inga problem.

Det som behövs sen är att typ kopiera det som finns i min websockets-branch, och sedan ändra i frontenden så att man skickar data till partykit-domänen istället.
